groups: []
resources:
- name: foo
  type: git
  source:
    private_key: rrrr
    uri: https://github.com/springernature/foo.git
- name: CF dev-ee-dev
  type: cf
  source:
    api: https://dev....com
    organization: ee
    password: ((cf-credentials.password))
    space: dev
    username: ((cf-credentials.username))
- name: CF live-ee-staging
  type: cf
  source:
    api: https://live...com
    organization: ee
    password: ((cf-credentials.password))
    space: staging
    username: ((cf-credentials.username))
- name: CF live-ee-live
  type: cf
  source:
    api: https://live...com
    organization: ee
    password: ((cf-credentials.password))
    space: live
    username: ((cf-credentials.username))
- name: CF ee-live
  type: cf
  source:
    api: https://some.custom.cf
    organization: ee
    password: ((cf-credentials.password))
    space: live
    username: ((cf-credentials.username))
- name: Docker Registry
  type: docker-image
  source:
    password: pass1
    repository: foo/bar
    username: user1
resource_types: []
jobs:
- name: run test.sh
  serial: true
  plan:
  - get: foo
    trigger: true
  - task: ./test.sh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
          tag: latest
      run:
        path: /bin/sh
        args:
        - -exc
        - ./test.sh
        dir: foo
      inputs:
      - name: foo
        path: ""
- name: run build.sh
  serial: true
  plan:
  - get: foo
    passed:
    - run test.sh
    trigger: true
  - task: ./build.sh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
          tag: latest
      run:
        path: /bin/sh
        args:
        - -exc
        - ./build.sh
        dir: foo
      inputs:
      - name: foo
        path: ""
- name: deploy-cf
  serial: true
  plan:
  - get: foo
    passed:
    - run build.sh
    trigger: true
  - put: CF dev-ee-dev
    params:
      environment_variables: {}
      manifest: manifest.yml
- name: deploy-cf (1)
  serial: true
  plan:
  - get: foo
    passed:
    - deploy-cf
    trigger: true
  - put: CF live-ee-staging
    params:
      environment_variables: {}
      manifest: manifest.yml
- name: deploy-cf (2)
  serial: true
  plan:
  - get: foo
    passed:
    - deploy-cf (1)
    trigger: true
  - put: CF live-ee-live
    params:
      environment_variables: {}
      manifest: manifest.yml
- name: deploy-cf (3)
  serial: true
  plan:
  - get: foo
    passed:
    - deploy-cf (2)
    trigger: true
  - put: CF ee-live
    params:
      environment_variables: {}
      manifest: manifest.yml
- name: run notify.sh
  serial: true
  plan:
  - get: foo
    passed:
    - deploy-cf (3)
    trigger: true
  - task: ./notify.sh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
          tag: latest
      run:
        path: /bin/sh
        args:
        - -exc
        - ./notify.sh
        dir: foo
      inputs:
      - name: foo
        path: ""
- name: docker-push
  serial: true
  plan:
  - get: foo
    passed:
    - run notify.sh
    trigger: true
  - put: Docker Registry
    params:
      build: foo

