groups: []
resources:
- name: foo
  type: git
  source:
    private_key: rrrr
    uri: https://github.com/springernature/foo.git
- name: Cloud Foundry
  type: cf
  source:
    api: https://dev....com
    organization: asd
    password: pwd1
    space: spacename1
    username: uname1
- name: Cloud Foundry (1)
  type: cf
  source:
    api: https://some.custom.cf
    organization: orgname2
    password: pwd2
    space: spacename2
    username: uname2
- name: Cloud Foundry (2)
  type: cf
  source:
    api: https://live...com
    organization: asd
    password: pwd3
    space: spacename3
    username: uname3
- name: Docker Registry
  type: docker-image
  source:
    password: pass1
    repository: foo/bar
    username: user1
resource_types: []
jobs:
- name: run test.sh
  serial: true
  plan:
  - get: foo
    trigger: true
  - task: ./test.sh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
          tag: latest
      run:
        path: /bin/sh
        args:
        - -exc
        - ./test.sh
        dir: foo
      inputs:
      - name: foo
        path: ""
- name: run build.sh
  serial: true
  plan:
  - get: foo
    passed:
    - run test.sh
    trigger: true
  - task: ./build.sh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
          tag: latest
      run:
        path: /bin/sh
        args:
        - -exc
        - ./build.sh
        dir: foo
      inputs:
      - name: foo
        path: ""
- name: deploy-cf
  serial: true
  plan:
  - get: foo
    passed:
    - run build.sh
    trigger: true
  - put: Cloud Foundry
    params:
      environment_variables: {}
      manifest: manifest.yml
- name: deploy-cf (1)
  serial: true
  plan:
  - get: foo
    passed:
    - deploy-cf
    trigger: true
  - put: Cloud Foundry (1)
    params:
      environment_variables: {}
      manifest: manifest.yml
- name: deploy-cf (2)
  serial: true
  plan:
  - get: foo
    passed:
    - deploy-cf (1)
    trigger: true
  - put: Cloud Foundry (2)
    params:
      environment_variables: {}
      manifest: manifest.yml
- name: run notify.sh
  serial: true
  plan:
  - get: foo
    passed:
    - deploy-cf (2)
    trigger: true
  - task: ./notify.sh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
          tag: latest
      run:
        path: /bin/sh
        args:
        - -exc
        - ./notify.sh
        dir: foo
      inputs:
      - name: foo
        path: ""
- name: docker-push
  serial: true
  plan:
  - get: foo
    passed:
    - run notify.sh
    trigger: true
  - put: Docker Registry
    params:
      build: foo

