groups: []
resources:
- name: halfpipe
  type: git
  source:
    uri: git@github.com:springernature/halfpipe.git
    branch: master
    private_key: ((deploy-keys.halfpipe))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:springernature/halfpipe.git
    branch: version
    file: version
    private_key: ((deploy-keys.halfpipe))

- name: release
  type: github-release
  source:
      owner: springernature
      repository: halfpipe
      access_token: ((api-keys.halfpipe))

resource_types: []
jobs:
- name: Test
  serial: true
  plan:
  - get: halfpipe
    trigger: true
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.9.2-alpine3.7
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          ls -al
          export GOPATH=$PWD
          cd src/github.com/springernature/halfpipe
          go test ./...
      inputs:
      - name: halfpipe
        path: /src/github.com/springernature/halfpipe
- name: Bump Major
  plan:
    - put: version
      params:
        {bump: major}
- name: Bump Minor
  plan:
    - put: version
      params:
        {bump: minor}
- name: Bump Patch
  plan:
    - put: version
      params:
        {bump: patch}

- name: Build and create github release
  plan:
    - aggregate:
      - get: halfpipe
        passed:
          - Test
      - get: version
        trigger: true
    - task: Build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: golang
            tag: 1.9.2-alpine3.7
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            export ROOT=$PWD
            export GOPATH=$PWD
            cd src/github.com/springernature/halfpipe
            CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -o halfpipe_darwin cmd/halfpipe.go
            CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o halfpipe_linux cmd/halfpipe.go
            cp halfpipe_darwin halfpipe_linux $ROOT/binaries
        inputs:
        - name: halfpipe
          path: src/github.com/springernature/halfpipe
        outputs:
        - name: binaries
    - put: halfpipe
      params:
        repository: halfpipe
        tag: version/version
    - put: release
      params:
        name: halfpipe/name
        tag: version/version
        globs:
          - binaries/halfpipe_*