groups: []
resources:
- name: halfpipe
  type: git
  source:
    branch: go1.11
    uri: https://github.com/springernature/halfpipe.git
jobs:
- name: test
  serial: true
  plan:
  - get: halfpipe
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.11-stretch
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          cd halfpipe
          ./build.sh ci
      inputs:
      - name: halfpipe
      caches:
      - path: ../../../halfpipe-cache
- name: build
  plan:
  - aggregate:
    - get: halfpipe
      trigger: true
      passed:
      - test
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.11-stretch
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          cd halfpipe
          export GOPATH=/halfpipe-cache/go
          export VERSION="0.0.0-test"
          export CONF_PKG="github.com/springernature/halfpipe/config"
          export LDFLAGS="-X ${CONF_PKG}.Version=${VERSION}"
          export LDFLAGS="${LDFLAGS} -X ${CONF_PKG}.VaultPrefix=springernature"
          export LDFLAGS="${LDFLAGS} -X ${CONF_PKG}.SlackWebhook=https://hooks.slack.com/services/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"
          echo "LDFLAGS=${LDFLAGS}"

          # Build binaries
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -o halfpipe_darwin_$VERSION -ldflags "${LDFLAGS}" cmd/halfpipe.go
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o halfpipe_linux_$VERSION -ldflags "${LDFLAGS}" cmd/halfpipe.go
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -o halfpipe_windows_$VERSION.exe -ldflags "${LDFLAGS}" cmd/halfpipe.go

          cp halfpipe_darwin_$VERSION halfpipe_linux_$VERSION halfpipe_windows_$VERSION.exe ../binaries
          ls -lah ../binaries
      inputs:
      - name: halfpipe
      outputs:
      - name: binaries
      caches:
      - path: ../../../halfpipe-cache
