groups: []
resources:
- name: halfpipe
  type: git
  source:
    uri: git@github.com:springernature/halfpipe.git
    branch: master
    private_key: ((github.private_key))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:springernature/halfpipe.git
    branch: version
    file: version
    private_key: ((github.private_key))

- name: release
  type: github-release
  source:
      owner: springernature
      repository: halfpipe
      access_token: ((api-keys.halfpipe-cli))

jobs:
- name: Test
  serial: true
  plan:
  - get: halfpipe
    trigger: true
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.10-alpine3.7
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          ls -al
          export GOPATH=$PWD
          cd src/github.com/springernature/halfpipe
          go test ./...
      inputs:
      - name: halfpipe
        path: /src/github.com/springernature/halfpipe

- name: End2EndTest
  serial: true
  plan:
  - get: halfpipe
    passed:
    - Test
    trigger: true
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: springerplatformengineering/halfpipe-fly
          tag: latest
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          export GOPATH=$PWD
          cd src/github.com/springernature/halfpipe
          go build -o halfpipe cmd/halfpipe.go
          cd e2e_test
          ./test.sh ../halfpipe
      inputs:
      - name: halfpipe
        path: /src/github.com/springernature/halfpipe

- name: Bump Major
  plan:
    - put: version
      params:
        {bump: major}
- name: Bump Minor
  plan:
    - put: version
      params:
        {bump: minor}
- name: Bump Patch
  plan:
    - put: version
      params:
        {bump: patch}

- name: Build and create github release
  disable_manual_trigger: true
  plan:
    - aggregate:
      - get: halfpipe
        passed:
          - End2EndTest
      - get: version
        trigger: true
    - task: Build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: golang
            tag: 1.10-alpine3.7
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            export ROOT=$PWD
            export GOPATH=$PWD
            export VERSION=`cat version/version`
            export LDFLAGS="-X main.version=$VERSION -X main.vaultPrefix=springernature -X github.com/springernature/halfpipe/model.docHost=docs.halfpipe.io"

            # Build binaries
            cd src/github.com/springernature/halfpipe
            CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -o halfpipe_darwin -ldflags "$LDFLAGS" cmd/halfpipe.go
            CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o halfpipe_linux -ldflags "$LDFLAGS" cmd/halfpipe.go
            cp halfpipe_darwin halfpipe_linux $ROOT/binaries

        inputs:
        - name: halfpipe
          path: src/github.com/springernature/halfpipe
        - name: version
        outputs:
        - name: binaries
    - put: halfpipe
      params:
        repository: halfpipe
        tag: version/version
    - put: release
      params:
        name: halfpipe/name
        tag: version/version
        globs:
          - binaries/halfpipe_*
