groups: []
resources:
- name: release
  type: github-release
  source:
    access_token: ((api-keys.halfpipe-cli))
    owner: springernature
    repository: halfpipe
- name: halfpipe
  type: git
  source:
    branch: master
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe.git
- name: version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe.git
resource_types: []
jobs:
- name: Test
  serial: true
  plan:
  - get: halfpipe
    trigger: true
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.10-alpine3.7
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          ls -al
          export GOPATH=$PWD
          cd src/github.com/springernature/halfpipe
          go test ./...
      inputs:
      - name: halfpipe
        path: /src/github.com/springernature/halfpipe
- name: Bump Major
  plan:
  - put: version
    params:
      bump: major
- name: Bump Minor
  plan:
  - put: version
    params:
      bump: minor
- name: Bump Patch
  plan:
  - put: version
    params:
      bump: patch
- name: Build and create github release
  disable_manual_trigger: true
  plan:
  - aggregate:
    - get: halfpipe
      passed:
      - End2EndTest
    - get: version
      trigger: true
  - task: Build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.10-alpine3.7
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          export ROOT="$PWD"
          export GOPATH="$PWD"
          export VERSION="$(cat version/version)"
          export DATE_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          export GIT_COMMIT="$(cat src/github.com/springernature/halfpipe/.git/ref)"
          export CONF_PKG="github.com/springernature/halfpipe/config"
          export LDFLAGS=""
          export LDFLAGS="${LDFLAGS} -X ${CONF_PKG}.Version=${VERSION}"
          export LDFLAGS="${LDFLAGS} -X ${CONF_PKG}.CompiledAt=${DATE_TIME}"
          export LDFLAGS="${LDFLAGS} -X ${CONF_PKG}.GitCommit=${GIT_COMMIT}"
          export LDFLAGS="${LDFLAGS} -X ${CONF_PKG}.VaultPrefix=springernature"
          export LDFLAGS="${LDFLAGS} -X ${CONF_PKG}.DocHost=docs.halfpipe.io"

          # Build binaries
          cd src/github.com/springernature/halfpipe
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -o halfpipe_darwin -ldflags "${LDFLAGS}" cmd/halfpipe.go
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o halfpipe_linux -ldflags "${LDFLAGS}" cmd/halfpipe.go
          cp halfpipe_darwin halfpipe_linux $ROOT/binaries
      inputs:
      - name: halfpipe
        path: src/github.com/springernature/halfpipe
      - name: version
        path: ""
      outputs:
      - name: binaries
        path: ""
  - put: halfpipe
    params:
      repository: halfpipe
      tag: version/version
  - put: release
    params:
      globs:
      - binaries/halfpipe_*
      name: halfpipe/name
      tag: version/version
- name: End2EndTest
  serial: true
  plan:
  - get: halfpipe
    passed:
    - Test
    trigger: true
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: springerplatformengineering/halfpipe-fly
          tag: latest
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          export GOPATH=$PWD
          cd src/github.com/springernature/halfpipe
          go build -o halfpipe cmd/halfpipe.go
          cd e2e_test
          ./test.sh ../halfpipe
      inputs:
      - name: halfpipe
        path: /src/github.com/springernature/halfpipe
